[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# Somnia Network Configuration
[rpc_endpoints]
somnia_testnet = "https://dream-rpc.somnia.network/"
somnia_mainnet = "https://api.infra.mainnet.somnia.network/"

[etherscan]
somnia_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://shannon-explorer.somnia.network/api" }
somnia_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.somnia.network/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
